# -*- coding: utf-8 -*-
"""Task1_Loan_Calculator_App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BAhg98QaM33YUX8Sd1g9nwliZ7T-SxSo
"""

!pip install streamlit pyngrok

!ngrok config add-authtoken 31vY62rKYaskFfadp7AWO4iCREX_7Y4wuERjMpBJomWzjrR4M

# Commented out IPython magic to ensure Python compatibility.
# %%writefile loan_calculator_app.py
# import streamlit as st
# import pandas as pd
# import matplotlib.pyplot as plt
# 
# st.set_page_config(page_title="Loan Calculator", page_icon="💰", layout="centered")
# 
# st.title("📊 Loan Calculator App")
# 
# # Inputs
# principal = st.number_input("Loan Amount (Principal)", min_value=0.0, value=10000.0, step=100.0)
# annual_rate = st.number_input("Annual Interest Rate (%)", min_value=0.0, value=5.0, step=0.1)
# years = st.number_input("Loan Term (Years)", min_value=1, value=5, step=1)
# 
# # Calculation
# monthly_rate = (annual_rate / 100) / 12
# months = years * 12
# 
# if monthly_rate == 0:
#     monthly_payment = principal / months
# else:
#     monthly_payment = principal * (monthly_rate * (1 + monthly_rate)**months) / ((1 + monthly_rate)**months - 1)
# 
# total_payment = monthly_payment * months
# total_interest = total_payment - principal
# 
# # Display results
# st.subheader("📈 Results")
# st.write(f"**Monthly Payment:** ${monthly_payment:,.2f}")
# st.write(f"**Total Payment:** ${total_payment:,.2f}")
# st.write(f"**Total Interest:** ${total_interest:,.2f}")
# 
# # Amortization Schedule
# balance = principal
# schedule = []
# for m in range(1, months+1):
#     interest = balance * monthly_rate
#     principal_paid = monthly_payment - interest
#     balance -= principal_paid
#     schedule.append([m, monthly_payment, principal_paid, interest, max(balance,0)])
# 
# df = pd.DataFrame(schedule, columns=["Month", "Payment", "Principal Paid", "Interest Paid", "Remaining Balance"])
# 
# st.subheader("📊 Amortization Schedule")
# st.dataframe(df.head(12))  # show first 12 months
# 
# # Chart
# st.subheader("📉 Loan Balance Over Time")
# fig, ax = plt.subplots(figsize=(8,4))
# ax.plot(df["Month"], df["Remaining Balance"], label="Remaining Balance", color="blue")
# ax.set_xlabel("Month")
# ax.set_ylabel("Balance ($)")
# ax.set_title("Loan Payoff Over Time")
# ax.legend()
# st.pyplot(fig)
#

from pyngrok import ngrok

ngrok.kill()
get_ipython().system_raw("streamlit run loan_calculator_app.py --server.port 8501 &")

public_url = ngrok.connect(8501)
print("Streamlit app running at:", public_url)